language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
      - ANDROID_TARGET=android-21
      - ANDROID_TARGET=android-24
  global:
      - ANDROID_API_LEVEL=25
      - ANDROID_BUILD_TOOLS_VERSION=25.0.1
      - ANDROID_ABI=armeabi-v7a
      - ADB_INSTALL_TIMEOUT=8 # minutes


android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        - extra-android-m2repository
        - sys-img-$ANDROID_ABI-$ANDROID_TARGET

before_script:
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
    - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew build --stacktrace

after_failure:
    - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml
