language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
      - EMULATOR_ENABLED=false
      #TODO enable when android tests will be available
      #- EMULATOR_ENABLED=true

#      - ANDROID_TARGET=android-21
#      - ANDROID_TARGET=android-24
  global:
      # Build settings
      - ANDROID_API_LEVEL=25
      - ANDROID_BUILD_TOOLS_VERSION=25.0.1
      - ANDROID_TARGET=android-21
      - ANDROID_ABI=armeabi-v7a

      # Environment values
      - ADB_INSTALL_TIMEOUT=8 # Minutes
      - MALLOC_ARENA_MAX=2 # Switch glibc to a memory conserving mode

      # Java Options
      # http://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts
      - export _JAVA_OPTIONS="-Xms256m -Xmx1280m"
      - secure: "Vw1H6h5X6JBZtz75zM/MIGWT24rpXnqADn61JXbVfg/2RS/jYWU921UNIh4BnD1TLFQdq8/TfWaafiqz4C/m4qHa93V4x7wJbEQllmntmVaUpzB+ELyvmTzddqVjmH/sH3bt3ezbKtGT04J8XmYgje3gGmZDChK1BV9XhOlqINIgzAA9WJDYJda4SyoqAxpvii5aDS+wvE6Mm5NJ+O2TwF0qqTz5lkffmUBvLNU6SzJESfs7iHyi5s6cSKRuGnibuXmS43iaKuBfW3KmO9O8Z2BcWKslj3yVdjK0lRzLyik7dKtKihceHU1+KDHNLG/0IzzsldjFMeQ2MrCXrHNUSskj36rUbFfRcXORCPuQ6HZO/Cex92YlGzWx2i2IXCfX85pNnKXqb4pdTBTbu00BXwMMk855yrUp5CG0aQq1VGwSz9Pvlj2Qa3parXKEcDmxfpO1gq/z7l0HSVKutOFU9mJsh3tXfaQRmcA4q7p6JUeOwzNOyb+5lW0KHNDbXN2G8EVLaPEqxhx8iu0L9b2JoNqCaZUxEbzQW5g41bYHzlqLQ0PlZaQ1Q6/sq7KfbeNKZ9Gak/BeRWCaHL/XaFvYNuf25S8aI8JFLt3tGwrB1+wb5eirKTFkchi41F9JhK8ItJUAoYgjsQJnHKAj4ks+AWOra1gTLx9xb80DUU8mHKs="

addons:
  apt:
    packages:
      - tree

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution

cache:
  directories:
    # Cache dirs under .gradle folder
    - $HOME/.gradle/caches
    - $HOME/.gradle/daemon      # Cache daemon logs
    - $HOME/.gradle/native      # Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     # Cache the gradle
    - $HOME/.android/build-cache

android:
    components:
        - tools # To get the new `repository-11.xml`
        - platform-tools
        - tools # To install Android SDK tools 25.1.x
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL

        # Latest artifacts in local repository
        - extra-android-m2repository

        # Specify at least one system image
        - sys-img-$ANDROID_ABI-$ANDROID_TARGET

before_script:
    - android list targets
    - if [ "$EMULATOR_ENABLED" = true ]; then script/runAndroidEmulator.sh; fi

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew build lint checkstyle findbugs testReport --stacktrace

after_failure:
    - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

after_script:
    # Publish artifacts on gh-pages only for develop branch
    -  if [ "${TRAVIS_BRANCH}" = "develop" ]; then script/pushArtifactsToGithub.sh; fi
