language: android
jdk: oraclejdk8
sudo: false

android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-25.0.1
        - android-25
        - extra-android-m2repository

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew build --stacktrace

after_failure:
    - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml
